tcp:
  ip: '0.0.0.0'
  port: 36364
ws:
  ip: '0.0.0.0'
  port: 11111
  url: 'ws://localhost'
controller: 'ExampleController'
logging:
  file:
    loglevel: 'INFO'
    filename: 'gizmo.ExampleController.log'
  console:
    loglevel: 'INFO'